version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - 18888:80
    volumes:
      - .:/work
    working_dir: /work
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 43306:3306
    hostname: db

  init:
    image: mysql:5.7
    volumes:
      - ./db:/work
    working_dir: /work
    depends_on:
      - db
    command:
      - ./init.sh
